# Generated by Django 3.1.7 on 2021-04-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('short_title', models.CharField(max_length=100, verbose_name='Короткое наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('version', models.CharField(max_length=200, unique=True, verbose_name='Версия')),
                ('date', models.DateField(verbose_name='Дата начала действия справочника этой версии')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=200, verbose_name='Значение элемента')),
                ('handbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.handbook', verbose_name='Родительский идентификатор')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
    ]
