# Generated by Django 3.1.7 on 2021-04-05 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandbookVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200, verbose_name='Версия')),
                ('date', models.DateField(verbose_name='Дата начала действия справочника этой версии')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочников',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='version',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Версия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handbook',
            name='version',
            field=models.CharField(max_length=200, verbose_name='Версия'),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('code', 'version', 'handbook'), name='unique_element'),
        ),
        migrations.AddConstraint(
            model_name='handbook',
            constraint=models.UniqueConstraint(fields=('title', 'version'), name='unique_version'),
        ),
        migrations.AddField(
            model_name='handbookversion',
            name='handbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.handbook', verbose_name='Справочник'),
        ),
    ]
