# Generated by Django 3.1.7 on 2021-04-05 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210405_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='handbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.handbook', verbose_name='Название справочника'),
        ),
        migrations.AlterField(
            model_name='handbook',
            name='version',
            field=models.CharField(help_text="Enter two numbers separated by a dot. Example: '1.1'.", max_length=200, validators=[django.core.validators.RegexValidator(message='Invalid enter', regex='\\d+\\.\\d+')], verbose_name='Версия'),
        ),
    ]
